version: '3'

services:
  database:
    build:
      context: ./docker/database
    environment:
      - MYSQL_DATABASE=tr-logic
      - MYSQL_USER=tr
      - MYSQL_PASSWORD=logic
      - MYSQL_ROOT_PASSWORD=1111
    volumes:
      - ./docker/database/dump.sql:/docker-entrypoint-initdb.d/data.sql

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8001:80"
      - "4433:443"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/var/www

